### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by HactarCE** [10se1ucgo/cue_sdk#7]
I encountered this when trying to run the `color_pulse` example, and when manually typing the commands from the tutorials. I'm running Python 2.7 on Windows 10 64-bit.

```
Traceback (most recent call last):
  File "C:\Users\USERNAME\Desktop\color_pulse.py", line 66, in <module>
    cue = CUESDK("C:\\Users\\USERNAME\\Desktop\\CUESDK\\bin\\x64\\CUESDK.x64_2013.dll")
  File "C:\Python27\lib\site-packages\cue_sdk\api.py", line 36, in __init__
    self._libcue = CDLL(dll_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

Other than the single line `cue = CUESDK(" ... ")` I did not modify the file at all.

**Comment by 10se1ucgo** [comment]
It seems that you're using a 32-bit version of Python on a 64-bit version of the DLL. Try using the 32-bit version of the DLL or get a 64-bit installation of Python.

You can check the architecture by running this code in the interpreter:

``` python
>>> import platform
>>> platform.architecture()
# Outputs this on 64-bit
('64bit', 'WindowsPE')
# This on 32-bit
('32bit', 'WindowsPE')
```

**Comment by HactarCE** [comment]
Thanks! Using the 32-bit DLL worked.
