### ISSUE TITLE
No way to close CUE dll

### ISSUE THREAD

**Issue by JiFish** [10se1ucgo/cue_sdk#8]
Unfortunately, due to corsair's bizarre design decisions, it is impossible to 'free' keys up once set and allow them to be controlled by the CUE software again. The only way to work around this is close the CUE dll itself which will free all keys.

However, this also isn't as easy as it seems. Destroying the cue_sdk object does not close the dll as expected. I have worked around the issue like this: (Where `self.cue` is the cue_sdk object.)
```
    def corsair_release(self):
        if (self.cue == None):
            return
        # setup kernel if needed
        if (self.k32 == None):
            import ctypes
            from ctypes import wintypes
            self.k32 = ctypes.WinDLL('kernel32')
            self.k32.FreeLibrary.argtypes = [wintypes.HMODULE]
        handle = self.cue._libcue._handle
        self.k32.FreeLibrary(handle)
        self.cue = None
```

Is there a better way to do this? Can something like this be implemented in to cue_sdk?

**Comment by finalised** [comment]
Was this fixed? Or did you end up finding a solution? Don't want to start a project and find out I can't give the CUE application back control.

**Comment by JiFish** [comment]
This wasn't fixed AFAIK. I continued to use the work-around I posted above.

**Comment by finalised** [comment]
Cheers mate for the speedy response, especially on such an old thread! I'll give it a go with your fix, or I might try another wrapper. Thanks again!

**Comment by JiFish** [comment]
If you find a wrapper that has this feature, please let me know!

**Comment by finalised** [comment]
I have yet to research it further, but I am fairly sure that the [CUE.NET](https://github.com/DarthAffe/CUE.NET) library written in C#, has a method `CueSDK.Reinitialize();` which does exactly what we're looking for.

**Comment by finalised** [comment]
Oh! This was fixed. Just use: `Corsair.ReleaseControl(CAM.ExclusiveLightingControl)`

**Comment by JiFish** [comment]
Oh nice! Thank you.

**Comment by 10se1ucgo** [comment]
My email is filled with a bunch of crap, I'm sorry I didn't see any of this earlier @_@
